plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'examples/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockNesting:
  Max: 4

# Line length configuration
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/**/*'

# More lenient configuration for routes.rb
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
  Max: 50
