require: ["rubocop-rails", "rubocop-performance", "rubocop-rspec", "rubocop-factory_bot"]
AllCops: { NewCops: enable, TargetRubyVersion: 3.2, Exclude: ["bin/**/*", "db/**/*", "tmp/**/*", "vendor/**/*", "node_modules/**/*"] }
Style/Documentation: { Enabled: false }
Style/FrozenStringLiteralComment: { Enabled: false }
Style/StringLiterals: { EnforcedStyle: double_quotes }
Style/ClassAndModuleChildren: { Enabled: false }
Style/GuardClause: { Enabled: false }
Metrics/BlockLength: { Exclude: ["spec/**/*", "test/**/*"] }
Layout/LineLength: { Max: 120 }
Naming/VariableName: { Enabled: false }
