name: Dependency Check

on:
  pull_request:
    branches: [ '*' ]

jobs:
  outdated:
    name: Check for Outdated Dependencies
    runs-on: ubuntu-22.04
    continue-on-error: true  # This ensures the check won't block PR merging

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.2'
        bundler-cache: true

    - name: Check for outdated gems
      id: outdated
      run: |
        echo "### Outdated Dependencies Report" >> $GITHUB_STEP_SUMMARY
        echo "The following dependencies have updates available:" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        bundle outdated | tee -a $GITHUB_STEP_SUMMARY || true
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Note: This is for information only and does not block merging. Updates are handled automatically by Dependabot." >> $GITHUB_STEP_SUMMARY

    - name: Comment on PR
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const fs = require('fs');
          const summary = fs.readFileSync(process.env.GITHUB_STEP_SUMMARY, 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: summary
          }); 