name: Ruby Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: simple_game_server_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/simple_game_server_test
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      SECRET_KEY_BASE: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true

    - name: Run linter
      run: bundle exec rubocop

    - name: Wait for PostgreSQL
      run: |
        while ! pg_isready -h localhost -p 5432; do
          echo "Waiting for PostgreSQL to start..."
          sleep 1
        done

    - name: Setup test database
      run: |
        bin/rails db:test:prepare

    - name: Run all tests
      run: |
        bin/rails test test:system 